### ISSUE TITLE
关于WebSockets

### ISSUE THREAD

**Issue by Broccolis** [dys-scientist/dys_danmu_crawler#2]
老哥你好，我在直播间F12看到的地址和你代码里的地址有些不一样，ws://idc-cn-xs.longzhu.com:8805/?room_id=''&connType=1，我试了下这个也是可以的，问一哈老哥，你代码里的地址从哪获取的。thx

**Comment by WenDesi** [comment]
可能是不同地域用的弹幕服务器不同

我人在深圳，我代码里的ip地址在广东省中山市
你代码的ip地址在浙江省杭州市

**Comment by Broccolis** [comment]
ok，I got it
